config:
  cloudflare:apiToken:
    secure: AAABAA7mnEqL8mrVWezOg3hMXK+bZmvhu6dJgQObfVXq0qw/T2/W3LA3lCbKWY/gqabtHDwgScV2r4j1chesaSWA6kp08wXJ
  mrwww:zoneid:
    secure: AAABAMODTVpOxzmCHLaslXAIUqx2/SSE3No++z8GmHidkpxZdBY297Xod0FIp96jnobh/m+6vyp27QmJO2tggQ==
  vercel:apiToken:
    secure: AAABADRHNkrJOqtHRyNnLGzYZFBX3T9mXcNhgBaZLHsNW1g5v5RAkjiskB0ByjnMntMn7CM4U34=
  vercel:team: team_Ade0MlfC3211ml3wYJZ4c9hn
